name: "Build individual target"
description: "Build individual target"

inputs:
  target:
    description: "make target to build"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - shell: bash
      run: |
        set -xe
        docker buildx create --use --platform=linux/arm64,linux/amd64 --name multi-platform-builder
        docker buildx inspect --bootstrap
        docker buildx install
        make DOCKER_BUILDX_FLAGS="--platform linux/amd64,linux/arm64 --push" ${{ inputs.target }}
        make test
