name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          set -xe
          docker buildx create --use --platform=linux/arm64,linux/amd64 --name multi-platform-builder
          docker buildx inspect --bootstrap
          docker buildx install
          make DOCKER_BUILDX_FLAGS="--platform linux/amd64,linux/arm64 --load" all
          make test
          make push
