name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  debian-fips:
    name: debian-fips
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-target
        with:
          postgresql_version: debian-fips
  xmlsec1-fips:
    needs:
      - debian-fips
    name: xmlsec1-fips
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-target
        with:
          postgresql_version: xmlsec1-fips
  python-fips:
    needs:
      - xmlsec1-fips
    name: python-fips
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-target
        with:
          postgresql_version: python-fips
  python-fips-full:
    needs:
      - python-fips
    name: python-fips-full
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-target
        with:
          postgresql_version: python-fips-full
